"""Add ingredient_conversions table

Revision ID: 359bc77bf9df
Revises: 
Create Date: 2026-08-07 22:26:54.057020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359bc77bf9df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit_name', sa.String(length=20), nullable=False),
    sa.Column('equivalent_in_grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'unit_name', name='uix_ingredient_unit')
    )
    with op.batch_alter_table('ingredient_conversions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingredient_conversions_ingredient_id'), ['ingredient_id'], unique=False)

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('ingredient_conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingredient_conversions_ingredient_id'))

    op.drop_table('ingredient_conversions')
    # ### end Alembic commands ###
